provider:
  osx: azure
  linux: azure
  win: azure
conda_forge_output_validation: true
github:
  user_or_org: qgist
azure:
  # flag for whether or not Azure should upload the packages
  # it builds to anaconda.org
  upload_packages: False
  # flag for forcing the building all supported providers
  force: False
channels:
  # sources selects the channels to pull packages from, in order.
  sources:
    - conda-forge
    - defaults
  # targets is a list of 2-lists, where the first element is the
  # channel to push to and the second element is the label on that channel
  targets:
    - ["qgist", "main"]
